#version 450

layout(local_size_x = 16, local_size_y = 16) in;

layout(set = 0, binding = 0) buffer InputBuffer {
    vec4 data[];
} inputBuffer;

layout(set = 0, binding = 1) buffer OutputBuffer {
    vec4 data[];
} outputBuffer;

void main() {
    // Calculate the linear index for the input and output arrays
    uint x = gl_GlobalInvocationID.x;
    uint y = gl_GlobalInvocationID.y;
    uint width = gl_NumWorkGroups.x * gl_WorkGroupSize.x;

    uint idx = x + y * width;

    // Copy the value from input to output
    outputBuffer.data[idx] = inputBuffer.data[idx];
    
}
