#version 450

layout(set = 0, binding = 0) buffer InputBuffer {
    vec4 pixels[];
} inputImage;

layout(set = 0, binding = 1) buffer OutputBuffer {
    vec4 pixels[];
} outputImage;

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

void main() {
    uint index = gl_GlobalInvocationID.y * gl_NumWorkGroups.x * 16 + gl_GlobalInvocationID.x;
    outputImage.pixels[index] = inputImage.pixels[index] * 2.0;
}
